language: go

go:
    - 1.9
    - "1.10"
    - tip

go_import_path: github.com/intel/ccloudvm

matrix:
  allow_failures:
  - go: tip

before_install:
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install

script:
   - go env
   - gometalinter --tests --vendor --disable-all --enable=misspell --enable=vet --enable=ineffassign --enable=gofmt --enable=gocyclo --cyclo-over=15 --enable=golint --enable=errcheck  --linter="errcheck:errcheck -abspath {not_tests=-ignoretests} -ignorepkg fmt:PATH:LINE:MESSAGE" --enable=deadcode ./...
